name: Run tests

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.7.0-beta3', '1.6.0-rc1', '1.5', '1.4', '1.0', 'nightly']
      fail-fast: false
    name: Test Julia ${{ matrix.julia-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - run: julia -e 'using Pkg; pkg"add Run@0.1"'
      - run: julia -e 'using Run; Run.prepare("test/environments/main")'
      - run: julia -e 'using Run; Run.test(project="test/environments/main")'
        env:
          JULIA_NUM_THREADS: "2"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          file: ./lcov.info
          flags: Run.test
          name: codecov-umbrella

  # A job that succeeds if and only if all jobs in `test` succeed.
  all-success:
    if: always() && github.event.pull_request
    needs: test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/tkf/merge-conclusions-action
      - uses: tkf/merge-conclusions-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
